### PR TITLE
Fix express version at 3.17 and update ffmpeg code

### PR DESCRIPTION
**Pull request by schickm**
Bumping up to express 4 is a bit more complex than I'm qualified to do (longtime js programmer, first time node programmer).  As discussed in #34, I set the express version 3.17, and I updated the ffmpeg code that reads the tags...now it's working again.  The app should be functional again out of the box.

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
Cool thanks Matt!  To clean up this PR, can you `git checkout config/config.json` (maybe back up your customized version first).  Then do a `git rebase -I HEAD~3` (rebase the last 3 commits of yours), change the `pick`s to `squash`s or just `s` edit commit message to just the first commit's, then `git push -f` (force push)?  Or SourceTree or whatever preferred method.  Also, I'm happy to see fluent changed their API to be error first in callbacks.  Can you also update the version of fluent in the manifest?

Also, I can manually handle the rebasing if you prefer?

**Comment by schickm** [comment]
I’m sorry Nick, but I’m totally confused when it comes to rebasing etc…not really sure how to go about that.  Thanks for the overview of the steps though.  I’m gonna have to ask you to take care of it, because I was left floundering with git commands.

**Comment by nickdesaulniers** [comment]
It's ok, it's certainly overwhelming until you get it right (utter chaos when rebasing goes wrong though), and then becomes muscle memory.  I've been meaning to write a blog post about this since I don't have a favorite reference I can just link people to.

**Comment by nickdesaulniers** [comment]
Thanks Matt, I [merged this](https://github.com/nickdesaulniers/audiostream/commits/master). Closing this PR.

**Comment by nickdesaulniers** [comment]
Matt, [maybe you can help me out with another project of mine](https://github.com/nickdesaulniers/What-Open-Source-Means-To-Me)?

**Pull request closed without merging**
